#!/bin/bash

while true; do
    echo "우분투가 재밌나요? (y/n)"
    read answer

    case $answer in
        [yY]*)
            echo "yes"
            break
            ;;
        [nN]*)
            echo "no"
            break
            ;;
        *)
            echo "yes or no로 입력하세요:"
            ;;
    esac
done
